# Generated by Django 5.0 on 2023-12-26 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='porfile_pic',
            new_name='profile_pic',
        ),
    ]
