# Generated by Django 5.0 on 2023-12-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_porfile_pic_custom_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_m',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='media/profile_pic'),
        ),
        migrations.AddField(
            model_name='job_m',
            name='deadline',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job_m',
            name='qualification',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
