# Generated by Django 5.0 on 2023-12-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_job_m_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_m',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='media/company_logo'),
        ),
    ]
