# Generated by Django 5.0 on 2023-12-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_job_m_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='cv',
            field=models.ImageField(null=True, upload_to='media/cv'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='skills',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
