# Generated by Django 5.0 on 2023-12-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_custom_user_cv_custom_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='cv',
            field=models.FileField(null=True, upload_to='media/cv'),
        ),
    ]
