# Generated by Django 5.0 on 2023-12-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_jobseekerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply_m',
            name='cv_apply',
            field=models.FileField(null=True, upload_to='media/cv_apply'),
        ),
        migrations.AddField(
            model_name='jobapply_m',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply_m',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.job_m'),
        ),
    ]
