# Generated by Django 5.0 on 2024-01-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_jobapply_m_cv_apply_jobapply_m_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply_m',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapply_m',
            name='cv_cover_latter',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobapply_m',
            name='excepted_salay',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapply_m',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapply_m',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/photo'),
        ),
        migrations.AddField(
            model_name='jobapply_m',
            name='signature',
            field=models.ImageField(null=True, upload_to='media/signature'),
        ),
    ]
